<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.opencloudb.route.function.PartitionByRangeDateHashTest" tests="2" skipped="0" failures="0" errors="0" timestamp="2017-02-16T07:06:17" hostname="DESKTOP-T7UG6RU" time="2.372">
  <properties/>
  <testcase name="testRange" classname="org.opencloudb.route.function.PartitionByRangeDateHashTest" time="0.001"/>
  <testcase name="test" classname="org.opencloudb.route.function.PartitionByRangeDateHashTest" time="2.365"/>
  <system-out><![CDATA[15:06:18.020   WARN [Test worker-SendThread(127.0.0.1:52324)] (ClientCnxn.java:1102) -Session 0x15a45be021d0000 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
